model = "gpt-5.2-codex"
model_reasoning_effort = "xhigh"
[projects."/home/nanda/projects/personal/building-blocks"]
trust_level = "trusted"

[projects."/home/nanda/projects/personal/doit-senior-test"]
trust_level = "trusted"

[projects."/home/nanda/projects/projectsprint/ps-landing-page"]
trust_level = "trusted"

[projects."/home/nanda/projects/projectsprint/building-block"]
trust_level = "trusted"

[notice]
hide_full_access_warning = true

[mcp_servers.chrome-devtools]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest", "--browser-url=http://127.0.0.1:9222"]
startup_timeout_sec = 20.0

[features]
unified_exec = true
shell_snapshot = true
steer = true

